<?php

declare(strict_types=1);

/**
 * Regenerate spec/ENDPOINTS.md from Close's published OpenAPI description.
 *
 *     php spec/build-inventory.php
 *
 * The inventory is checked in so that "what does Close offer, and how much of
 * it does this package wrap" is answerable without a network call, and so that
 * a diff shows when Close adds or removes an operation. Re-run it when
 * something looks missing.
 *
 * The spec itself is deliberately not committed: it is 1.4 MB, it changes
 * without notice, and every fact this package depends on is either in the
 * generated inventory or written down in DESIGN.md with the reasoning attached.
 *
 * Note the two "schema" columns. Close's spec types roughly half its
 * operations and gives the rest an example only, which is the reason this
 * package is hand-written rather than generated — see DESIGN.md. A blank in
 * either column means anything built for that operation was inferred from one
 * example.
 */
const SPEC_URL = 'https://api.close.com/api/openapi.json';
const OUTPUT = __DIR__.'/ENDPOINTS.md';

$json = file_get_contents(SPEC_URL);

if ($json === false) {
    fwrite(STDERR, 'Could not fetch '.SPEC_URL."\n");
    exit(1);
}

/** @var array{paths: array<string, array<string, mixed>>, info: array{version?: string}} $spec */
$spec = json_decode($json, true, 512, JSON_THROW_ON_ERROR);

$methods = ['get', 'post', 'put', 'patch', 'delete'];
$groups = [];
$operations = 0;
$typedRequests = 0;
$typedResponses = 0;
$withBody = 0;

foreach ($spec['paths'] as $path => $item) {
    foreach ($item as $method => $operation) {
        if (! in_array($method, $methods, true) || ! is_array($operation)) {
            continue;
        }

        $operations++;

        $tag = $operation['tags'][0] ?? '(untagged)';

        $responseSchema = false;

        foreach ($operation['responses'] ?? [] as $code => $response) {
            if (str_starts_with((string) $code, '2') && isset($response['content']['application/json']['schema'])) {
                $responseSchema = true;
                break;
            }
        }

        $body = $operation['requestBody']['content']['application/json'] ?? null;
        $requestSchema = isset($body['schema']);

        if ($body !== null) {
            $withBody++;
        }

        $typedResponses += $responseSchema ? 1 : 0;
        $typedRequests += $requestSchema ? 1 : 0;

        $groups[$tag][] = [
            'method' => strtoupper($method),
            'path' => $path,
            'id' => $operation['operationId'] ?? '',
            'summary' => $operation['summary'] ?? '',
            'request' => $body === null ? '—' : ($requestSchema ? 'yes' : 'example'),
            'response' => $responseSchema ? 'yes' : 'example',
        ];
    }
}

ksort($groups);

$out = [];
$out[] = 'Close API endpoint inventory';
$out[] = '============================';
$out[] = '';
$out[] = sprintf(
    'Generated by `php spec/build-inventory.php` from %s on %s. Spec version %s.',
    SPEC_URL,
    date('j F Y'),
    $spec['info']['version'] ?? 'unknown',
);
$out[] = '';
$out[] = sprintf(
    '**%d operations across %d paths and %d tags.** %d have a typed 2xx response schema and %d do '
    .'not; of the %d that take a request body, %d are typed. The untyped half is why this package '
    .'is hand-written rather than generated — see DESIGN.md.',
    $operations,
    count($spec['paths']),
    count($groups),
    $typedResponses,
    $operations - $typedResponses,
    $withBody,
    $typedRequests,
);
$out[] = '';
$out[] = '**This inventory is not complete, because the spec is not.** `POST /data/search/` — the';
$out[] = 'Advanced Filtering API, and the only way to find a lead by anything but its id — appears';
$out[] = 'nowhere in it. Treat an absence here as a question rather than an answer.';
$out[] = '';
$out[] = 'To see what this package wraps: `grep -rn "return \'" src/Resource/*.php` gives every';
$out[] = 'collection path, and `tests/Resource/ResourceTest.php` enumerates every method and URL the';
$out[] = 'resources produce. Everything else is reachable through `Close::transport()`.';
$out[] = '';

foreach ($groups as $tag => $rows) {
    usort($rows, static fn (array $a, array $b): int => [$a['path'], $a['method']] <=> [$b['path'], $b['method']]);

    $out[] = '## '.$tag;
    $out[] = '';
    $out[] = '| | path | operation | req schema | resp schema |';
    $out[] = '|---|---|---|---|---|';

    foreach ($rows as $row) {
        $out[] = sprintf(
            '| %s | `%s` | %s | %s | %s |',
            $row['method'],
            $row['path'],
            $row['id'],
            $row['request'],
            $row['response'],
        );
    }

    $out[] = '';
}

file_put_contents(OUTPUT, implode("\n", $out));

printf("Wrote %s: %d operations, %d tags.\n", OUTPUT, $operations, count($groups));
